name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '50 22 * * 5'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install deps
      run: npm i
    - name: Get the data and analyze
      run: |
        node download-lidar-hd.js
      shell: bash
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
